name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    branches: 
        - main


jobs:
  deploy:
    name: Terraform Deploy
    environment: main_approved
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_AK}}
          aws-secret-access-key: ${{ secrets.AWS_SK }}
          aws-region: us-east-1
      - name: Initialise project and plan
        run: |
          cd terraform
          terraform init -input=false
          terraform plan
      - name: Deploy terraform
        run: |
          cd terraform
          terraform apply -auto-approve
